# Generated by Django 4.2.28 on 2026-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('cover', models.ImageField(null=True, upload_to='images/')),
                ('Description', models.CharField(max_length=600)),
            ],
        ),
    ]
